# Generated by Django 4.2.1 on 2023-06-01 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uloge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='korisnik',
            name='role',
        ),
        migrations.AddField(
            model_name='predmeti',
            name='nositelj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nositelj', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Upis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('upisan', 'Upisan'), ('neupisan', 'Neupisan')], max_length=50)),
                ('predmet_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predmet', to='app.predmeti')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='korisnik',
            name='uloge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uloge', to='app.uloge'),
        ),
    ]
