# Generated by Django 4.2.1 on 2023-06-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uloge_remove_korisnik_role_predmeti_nositelj_upis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uloge',
            name='name',
        ),
        migrations.AddField(
            model_name='uloge',
            name='uloga',
            field=models.CharField(choices=[('admin', 'Admin'), ('profesor', 'Profesor'), ('student', 'Student')], max_length=20, null=True),
        ),
    ]
