# Generated by Django 4.2.1 on 2023-06-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_uloge_name_uloge_uloga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uloge',
            name='uloga',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PROFESOR', 'Profesor'), ('STUDENT', 'Student')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='upis',
            name='status',
            field=models.CharField(choices=[('upisan', 'Upisan'), ('polozen', 'Polozen'), ('izgubio potpis', 'Izgubio potpis')], max_length=50),
        ),
    ]
