# Generated by Django 4.2.1 on 2023-06-08 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_uloge_uloga_alter_upis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmeti',
            name='upisi',
            field=models.ManyToManyField(through='app.Upis', to=settings.AUTH_USER_MODEL),
        ),
    ]
