# Generated by Django 4.2.1 on 2023-06-08 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_predmeti_upisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmeti',
            name='upisi',
            field=models.ManyToManyField(related_name='predmeti_upis', through='app.Upis', to=settings.AUTH_USER_MODEL),
        ),
    ]
