# Generated by Django 4.2.1 on 2023-06-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_predmeti_upisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uloge',
            name='uloga',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('PROFESOR', 'profesor'), ('STUDENT', 'student')], max_length=20, null=True),
        ),
    ]
